### ISSUE TITLE
TODO : Fix / Enhancement lists

### ISSUE THREAD

**Issue by yskim0** [snuviplab/snuviplab.github.io#4]
- [ ] mathjax inline 오류 
- [ ] author 등록 및 모든 포스팅에 적용
- [ ] 폰트 등 기본 레이아웃 조금 더 가독성있게 변경
- [ ] Update `About` Page 
- [ ] Modify `Readme.md`
